### ISSUE TITLE
"Unknown BER" in Info column for PaymentDetailsReq

### ISSUE THREAD

**Issue by JeremyWhaling** [ChargePoint/wireshark-v2g#54] opened 2023-12-14 01:23 UTC
For PnC sessions, I am seeing the info column as "Unknown BER" for the "PaymentDetailsReq" message. Protocol column also shows "BER" instead of "ISO1". I can provide PCAPs if necessary to show this. This does not appear to show in EIM sessions as I believe the PaymentDetailsReq/Res messages are skipped.
![BER](https://github.com/ChargePoint/wireshark-v2g/assets/9215150/55bf9193-53b0-4984-8cf2-70da5114b93e)

**Comment by chardin-cpi** [comment] 2023-12-14 02:15
we try to use a BER decoder for certificates - the problem is that if the decoder fails on an invalid cert there isn't a great way to find the error to my knowledge - so, yes sending some pcaps would help but check the certs in use on the test since that is the interlock on the BER encoding.

cc: @jhart-cpi @pthompson-cpi

**Comment by barsnick** [comment] 2023-12-14 08:43
I consider this a display issue, that the BER error is propagated to the Protocol and Info columns. (I have no idea how to avoid it, yet.)

**Comment by barsnick** [comment] 2023-12-14 09:42
It's also unfortunate that the Wireshark certificate function throws the BER error (and apparently propagates it), but the BER error is not visible in the display of the certificate, which I assume is also a Wireshark function - the "ber" dissector.

![Screenshot 2023-12-14 102702](https://github.com/ChargePoint/wireshark-v2g/assets/7283222/bd498ef7-3ba9-4875-9558-7780616c1437)

**Comment by chardin-cpi** [comment] 2024-02-29 20:55
so, I tried a few things to try and fix this and just haven't been able to - I am willing to take a patch that someone comes up with but I ran out of ideas.

closing this ticket since I am not sure if it can be fixed on how Wireshark propagates the errors.

**Closed by chardin-cpi** 2024-02-29 20:55 UTC
